;this file for FamiTone2 library generated by text2data tool
;edited by Doug Fraker, 2016, to add volume column

bgmbegin_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env3,@env9,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $07
	.word @env7,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cd,$ca,$c8,$c6,$c4,$c3,$c1,$c0,$00,$08
@env2:
	.byte $cf,$cd,$ca,$c7,$c5,$c4,$c3,$c1,$c1,$c0,$00,$09
@env3:
	.byte $cf,$05,$c0,$00,$02
@env4:
	.byte $cf,$cf,$cd,$cb,$ca,$00,$04
@env5:
	.byte $cf,$cb,$c6,$c3,$c0,$00,$04
@env6:
	.byte $cf,$ce,$02,$cd,$cb,$c8,$c6,$c5,$c5,$c4,$02,$c3,$02,$c2,$c1,$c0
	.byte $00,$0f
@env7:
	.byte $cf,$cf,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c7,$c7,$c5,$c4,$c1,$c0,$00
	.byte $0e
@env8:
	.byte $cf,$00,$00
@env9:
	.byte $c0,$bb,$b6,$b1,$ac,$a7,$a2,$9d,$98,$00,$08


@song0ch0:
@ref0:
	.byte $8c,$28,$81,$29,$81
@song0ch0loop:
@ref1:
	.byte $7f,$8c,$2a,$85,$7a,$28,$81,$27,$81,$28,$85,$27,$81,$25,$81
@ref2:
	.byte $27,$85,$25,$81,$23,$81,$25,$81,$21,$81,$23,$81,$25,$81
@ref3:
	.byte $1e,$9d
@ref4:
	.byte $93,$27,$81,$28,$81,$29,$81
@ref5:
	.byte $7a,$2a,$85,$28,$81,$27,$81,$28,$85,$27,$81,$25,$81
@ref6:
	.byte $27,$85,$25,$81,$23,$81,$36,$85,$36,$85
@ref7:
	.byte $1e,$9d
	.byte $ff,$07
	.word @ref4
	.byte $ff,$0c
	.word @ref5
	.byte $ff,$0e
	.word @ref2
@ref11:
	.byte $20,$81,$23,$81,$1e,$81,$20,$89,$76,$1e,$81,$20,$81
@ref12:
	.byte $83,$76,$2a,$81,$2c,$81,$2a,$81,$28,$81,$25,$81,$23,$81,$25,$81
@ref13:
	.byte $7a,$2a,$81,$28,$81,$27,$81,$28,$91
@ref14:
	.byte $83,$74,$8e,$1e,$81,$1c,$81,$1e,$81,$7a,$8c,$28,$81,$2a,$81,$2c
	.byte $81,$28,$81
@ref15:
	.byte $2a,$9d
@ref16:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref17:
	.byte $74,$8e,$20,$81,$1f,$81
@song0ch1loop:
@ref18:
	.byte $7a,$88,$23,$85,$7c,$88,$12,$81,$12,$81,$12,$81,$12,$81,$7a,$8e
	.byte $23,$81,$7c,$88,$12,$81
@ref19:
	.byte $7a,$8e,$23,$81,$7c,$88,$12,$81,$7a,$8e,$21,$81,$7c,$88,$12,$81
	.byte $7a,$8e,$21,$81,$7c,$88,$12,$81,$7a,$8e,$1e,$81,$7c,$88,$12,$81
@ref20:
	.byte $7a,$8e,$19,$85,$88,$12,$81,$12,$81,$12,$81,$12,$85,$12,$81
@ref21:
	.byte $83,$12,$85,$12,$81,$12,$81,$12,$81,$12,$81,$12,$81
@ref22:
	.byte $7a,$8e,$23,$85,$7c,$88,$12,$81,$12,$81,$12,$81,$12,$81,$7a,$8e
	.byte $23,$81,$7c,$88,$12,$81
@ref23:
	.byte $7a,$8e,$23,$81,$7c,$88,$12,$81,$7a,$8e,$21,$81,$7c,$88,$12,$7a
	.byte $8a,$23,$8e,$24,$85,$7a,$23,$85
@ref24:
	.byte $7a,$19,$85,$88,$12,$81,$12,$81,$12,$81,$12,$85,$12,$81
@ref25:
	.byte $83,$12,$85,$19,$81,$1e,$81,$12,$81,$12,$81,$12,$81
	.byte $ff,$0e
	.word @ref22
	.byte $ff,$10
	.word @ref19
@ref28:
	.byte $8e,$1c,$85,$24,$81,$25,$81,$7c,$88,$12,$81,$12,$81,$7a,$8e,$24
	.byte $81,$25,$81
@ref29:
	.byte $87,$7c,$88,$10,$81,$10,$85,$10,$85,$10,$81
@ref30:
	.byte $87,$7a,$8e,$23,$81,$21,$89,$75,$88,$28,$81,$28,$81
@ref31:
	.byte $28,$81,$28,$85,$28,$81,$28,$89,$7a,$8e,$22,$81
@ref32:
	.byte $23,$89,$75,$88,$2a,$81,$2a,$81,$2a,$81,$2a,$85
@ref33:
	.byte $1e,$85,$1e,$85,$1e,$85,$1e,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref34:
	.byte $87
@song0ch2loop:
@ref35:
	.byte $80,$12,$85,$86,$28,$81,$80,$12,$89,$86,$28,$85
	.byte $ff,$08
	.word @ref35
	.byte $ff,$08
	.word @ref35
@ref38:
	.byte $80,$12,$85,$86,$28,$81,$80,$12,$89,$86,$28,$81,$28,$81
	.byte $ff,$08
	.word @ref35
	.byte $ff,$08
	.word @ref35
	.byte $ff,$08
	.word @ref35
	.byte $ff,$0a
	.word @ref38
	.byte $ff,$08
	.word @ref35
	.byte $ff,$08
	.word @ref35
@ref45:
	.byte $80,$10,$85,$86,$28,$81,$80,$10,$89,$86,$28,$85
@ref46:
	.byte $80,$10,$85,$86,$28,$81,$80,$10,$89,$86,$28,$81,$28,$81
@ref47:
	.byte $80,$0e,$85,$86,$28,$81,$80,$0e,$89,$86,$28,$85
	.byte $ff,$08
	.word @ref47
	.byte $ff,$08
	.word @ref45
@ref50:
	.byte $80,$10,$85,$86,$28,$81,$28,$85,$28,$85,$28,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref51:
	.byte $87
@song0ch3loop:
@ref52:
	.byte $7f,$82,$09,$85,$84,$0c,$85,$82,$09,$85,$84,$0c,$85
@ref53:
	.byte $82,$09,$85,$84,$0c,$85,$82,$09,$81,$09,$81,$84,$0c,$85
@ref54:
	.byte $82,$09,$85,$84,$0c,$85,$82,$09,$85,$84,$0c,$85
@ref55:
	.byte $82,$09,$85,$84,$0c,$85,$82,$09,$85,$84,$0c,$81,$0c,$81
	.byte $ff,$08
	.word @ref52
	.byte $ff,$0a
	.word @ref53
	.byte $ff,$08
	.word @ref54
	.byte $ff,$0a
	.word @ref55
	.byte $ff,$08
	.word @ref52
	.byte $ff,$0a
	.word @ref53
	.byte $ff,$08
	.word @ref54
	.byte $ff,$0a
	.word @ref55
	.byte $ff,$08
	.word @ref52
	.byte $ff,$0a
	.word @ref53
@ref66:
	.byte $82,$09,$85,$84,$0c,$85,$82,$09,$85,$84,$0c,$81,$82,$09,$81
@ref67:
	.byte $09,$85,$84,$0c,$81,$0c,$85,$0c,$85,$0c,$81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
	.byte $fb,$04
@ref68:
	.byte $fb,$06,$83,$fb,$04,$83
@song0ch4loop:
@ref69:
	.byte $fb,$06,$83,$fb,$04,$83,$fb,$06,$83,$fb,$04,$83,$fb,$06,$83,$fb
	.byte $04,$83,$fb,$06,$83,$fb,$04,$83
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref69
	.byte $fd
	.word @song0ch4loop
