;this file for FamiTone2 libary generated by nsf2data tool

sfxstart:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$bb,$81,$bd,$82,$00,$01,$80,$ba,$01,$80,$b9,$01,$80,$b8,$01
	.byte $80,$bb,$81,$5e,$01,$80,$ba,$01,$80,$b9,$01,$80,$b8,$02,$80,$b7
	.byte $01,$80,$b6,$02,$80,$b5,$01,$80,$b4,$02,$80,$b3,$02,$80,$b2,$04
	.byte $80,$b1,$03,$00
