;this file for FamiTone2 libary generated by nsf2data tool

sfxtext:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$78,$81,$d5,$82,$00,$01,$80,$75,$01,$80,$73,$01,$80,$72,$01
	.byte $80,$71,$03,$00
